name: Check Code Formatting

on:
  push:
    branches:
      - "*"

jobs:
  prettier-check:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Prettier
        run: bun add prettier

      - name: Check Code Formatting with Prettier
        run: bun run prettier --check .
